<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputFamilyName</name>
   <tag></tag>
   <elementGuidId>2df7a594-1849-47fd-90f0-e33c55b99657</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'familyName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fr1830-field</value>
      <webElementGuid>77950333-462b-4770-b6bc-8c1a6634ea66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>familyName</value>
      <webElementGuid>4f978022-7c12-4087-ba14-f9c7cd6a0c39</webElementGuid>
   </webElementProperties>
</WebElementEntity>
